### ISSUE TITLE
Replace open graph image

### ISSUE THREAD

**Issue by anyulled** [barcelonajug/jbcnconf_web#991]
The current image is referencing the 2019 edition

![Open graph image](https://www.jbcnconf.com/2021/assets/img/logos/og-image.png)

**Comment by anyulled** [comment]
replacing with 
![2021 edition](https://github.com/barcelonajug/jbcnconf_web/blob/feature/replace_open_graph_image/2021/assets/img/logos/og-image.png?raw=true)

**Comment by abelsromero** [comment]
where is this used?

**Comment by anyulled** [comment]
> where is this used?

**Facebook**
![image](https://user-images.githubusercontent.com/100741/124348083-3dc2bc00-dbe8-11eb-8e6f-fc1e382cd977.png)

**Linkedin**
![image](https://user-images.githubusercontent.com/100741/124348107-5cc14e00-dbe8-11eb-8e64-c691091f434b.png)

**Twitter**
![image](https://user-images.githubusercontent.com/100741/124348141-8da18300-dbe8-11eb-9c72-492182214ad7.png)

**Comment by abelsromero** [comment]
Can we add a note to the readme, we are going to forget that next year XD

**Comment by anyulled** [comment]
> Can we add a note to the readme, we are going to forget that next year XD

done! thanks for the suggestion
